default: 'development'

development:
  database: 'db/development.sqlite3'

test:
  database: 'db/test.sqlite3'

uat:
  database: '/data/tags/uat.sqlite3'

production:
  database: '/data/tags/production.sqlite3'
